# Generated by Django 5.0.2 on 2024-02-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='added_by',
            new_name='owner',
        ),
    ]
